FROM thejunys/node-nginx:latest

MAINTAINER <thejunys@naver.com>

COPY ./ /react
COPY ./nginx/sites-available /etc/nginx/sites-available

WORKDIR /react

RUN npm install -y
RUN npm run build

CMD ["nginx", "-g", "daemon off;"]
